// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKMc37cJBNA8iCNXmtfHj3R9zXOIvdto',
    appId: '1:164535431568:web:9ad4f0c93460abe3854315',
    messagingSenderId: '164535431568',
    projectId: 'aptnote-30ef5',
    authDomain: 'aptnote-30ef5.firebaseapp.com',
    storageBucket: 'aptnote-30ef5.firebasestorage.app',
    measurementId: 'G-SVPSHZ6107',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTYcguaYtaTEwa4tXwMAQwT2Nj7TD7gEA',
    appId: '1:164535431568:android:dd98c3915ce411c5854315',
    messagingSenderId: '164535431568',
    projectId: 'aptnote-30ef5',
    storageBucket: 'aptnote-30ef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdcDBZsxvCbeUAiWN3spQ6AeOrT2PpP8A',
    appId: '1:164535431568:ios:c2b9dc75c6b1cf3a854315',
    messagingSenderId: '164535431568',
    projectId: 'aptnote-30ef5',
    storageBucket: 'aptnote-30ef5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdcDBZsxvCbeUAiWN3spQ6AeOrT2PpP8A',
    appId: '1:164535431568:ios:c2b9dc75c6b1cf3a854315',
    messagingSenderId: '164535431568',
    projectId: 'aptnote-30ef5',
    storageBucket: 'aptnote-30ef5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSKMc37cJBNA8iCNXmtfHj3R9zXOIvdto',
    appId: '1:164535431568:web:c4d81e9f231f0d07854315',
    messagingSenderId: '164535431568',
    projectId: 'aptnote-30ef5',
    authDomain: 'aptnote-30ef5.firebaseapp.com',
    storageBucket: 'aptnote-30ef5.firebasestorage.app',
    measurementId: 'G-DQ4EKEHBDQ',
  );
}
